import Head from 'next/head';

import twomind from '../assets/twomind.jpg';
import Logo from '../assets/logo.svg';

export default function Home() {
  return (
    <div>
      <Head>
        <title>TwoMind Soft Tech | Desenvolvimento de Software!</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>Olá mundo</h1>
        <img src={twomind} alt="Boneco" />
        <Logo />
      </main>
    </div>
  );
}